name:                MiniDumper
version:             0.1.0.0
github:              " julian-becker/MiniDumper"
license:             BSD3
author:              "Julian Becker"
maintainer:          "becker.julian@gmail.com"
copyright:           " Julian Becker"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            microservice

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/ julian-becker/MiniDumper#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs:
    - src

executables:
  MiniDumper-exe:
    main:                Main.hs
    source-dirs:         server
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - MiniDumper

tests:
  MiniDumper-test:
    main:                Spec.hs
    source-dirs:         server-test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - MiniDumper
